### PR TITLE
fix setup

### PR DESCRIPTION
**Pull request by malikshi**
- fix typo dnsproxy.xml
- fix dnsproxy-setup.sh but force to use curl for checking latest version
- parsing tab/spaces Makefile

### CODE REVIEW

**Comment by malikshi** [comment]
do we need WatchdogSec ?

**Comment by joshcangit** [comment]
Thanks for fixing the Makefile.

I thought removing `xh` would suffice.
```
3c3
< CMDS=$(type -P {aria2c,xh,curl,wget})
---
> CMDS=$(type -P {aria2c,curl,wget})
6d5
<     *xh*) xh HEAD $1 --no-check-status -h;;
20,21d18
<     *xh*)
<     xh -Fd $URL -o "$TMP_DIR/$FILE" Accept-Encoding:'zstd, gzip, deflate';;
```

For me, using `xh` was pretty fast but that was on my Ubuntu PC.
It also worked on `Termux` but strangely wouldn't work on Termux:Tasker.

I made that function for checking whichever utility is available.
Whether it's `xh`, `curl`, or `wget`.
Any of the 3 can check for the latest version.
Maybe `xh` might have given you problems but I doubt `wget` would be problematic.

I guess you had your reasons to make the script only use `curl` for that to work.
If that is the case, then I'll merge anyway.

**Comment by joshcangit** [comment]
> do we need WatchdogSec ?

Oh, I took that from the `systemd-resolved.service` file without thinking much.
I think that line might not be needed.
I wonder what else from that service file is not needed.
If so, should I wait for you to edit the service file?

**Comment by joshcangit** [comment]
Thanks for fixing the Makefile.

I was considering to remove `xh`
```
3c3
< CMDS=$(type -P {aria2c,xh,curl,wget})
---
> CMDS=$(type -P {aria2c,curl,wget})
6d5
<     *xh*) xh HEAD $1 --no-check-status -h;;
20,21d18
<     *xh*)
<     xh -Fd $URL -o "$TMP_DIR/$FILE" Accept-Encoding:'zstd, gzip, deflate';;
```

For me, using `xh` was pretty fast but that was on my Ubuntu PC.
It also worked on `Termux` but strangely wouldn't work on Termux:Tasker.
Maybe `xh` might have given you problems but I doubt `wget` would have been problematic.

**Comment by malikshi** [comment]
> For me, using `xh` was pretty fast but that was on my Ubuntu PC.
> It also worked on `Termux` but strangely wouldn't work on Termux:Tasker.
> Maybe `xh` might have given you problems but I doubt `wget` would have been problematic.

i didn't really use xh. i test the script with RPI4B and debian VPS's

> > do we need WatchdogSec ?
> 
> Oh, I took that from the `systemd-resolved.service` file without thinking much. I think that line might not be needed. I wonder what else from that service file is not needed. If so, should I wait for you to edit the service file?

is it good now?

**Comment by malikshi** [comment]
add priority dns, use resolv head instead of resolv tail.

**Pull request merged**
